version: '3.7'
services:
  node:
    container_name: app
    build: ./
    ports:
      - '3001:8080'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - gamebook-network
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - gamebook-network
    volumes:
      - gamebook-datas:/data/db
    ports:
      - '27017:27017'
volumes:
  gamebook-datas:
    name: gamebook-datas-volume

networks:
  gamebook-network:
    driver: bridge
