version: '3.7'
services:
  node:
    container_name: app
    build: ./
    ports:
      - '3001:8080'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    networks:
      - gamebook-network
    depends_on:
      - neo4j
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    networks:
      - gamebook-network
    volumes:
      - gamebook-datas:/data
volumes:
  gamebook-datas:
    name: gamebook-datas-volume

networks:
  gamebook-network:
    driver: bridge
